name: Backend Render Deploy

on:
  push:
    branches:
      - main

jobs:
  test-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 14.21

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests
        run: npm run test

      - name: Deploy to Render
        if: success()
        run: |
          curl -X POST \
            https://api.render.com/deploy/${{ secrets.BACKEND_ID }}?key=2Cau52g5CZE \
            -H "Authorization: Bearer ${{ secrets.API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"gitCommit": "${{ github.sha }}"}'
